<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xbs.flowcart</groupId>
        <artifactId>catalog-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>catalog-implementation</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.xbs.flowcart</groupId>
            <artifactId>catalog-api-contract</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xbs.flowcart</groupId>
            <artifactId>catalog-domain-events</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</project>