server.port=8081
spring.application.name=catalog-service
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/flowcart_catalog?authSource=admin
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG