version: '3.8'

services:
  catalog-db:
    image: mongo:latest
    container_name: flowcart-catalog-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=flowcart_catalog
    volumes:
      - catalog_data:/data/db
    networks:
      - flowcart-net

volumes:
  catalog_data:

networks:
  flowcart-net:
    driver: bridge