services:
  catalog-db:
    image: mongo:latest
    container_name: flowcart-catalog-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - flowcart-net

networks:
  flowcart-net:
    name: flowcart-net
    driver: bridge